### PR TITLE
[DOC] Implement dataset module and add new documentation

### PR DESCRIPTION
**Pull request by felipeffm**
Discuss:

how make documentation more readable for all:
    Sugestion: separe advanced concepts and make it visual

how to simplify the code at examples. 
   Sugestion: preprocess outside code

### CODE REVIEW

**Comment by felipeangelimvieira** [comment]
Related issue #102

**Comment by felipeangelimvieira** [comment]
@felipeffm  as we've talked today, I think it would be nice to have a structure similar to [sktime](https://github.com/sktime/sktime/blob/main/sktime/datasets/_single_problem_loaders.py), with one function for each dataset
I liked the idea of having a file with common plotting functions used in the documentation examples as you are implementing. Thank you very much for proposing this PR :)

**Comment by fkiraly** [comment]
might this also be relevant?
https://github.com/sktime/sktime/pull/4333

**Comment by felipeangelimvieira** [comment]
> might this also be relevant? [sktime/sktime#4333](https://github.com/sktime/sktime/pull/4333)

yes! Felipe told me he won't be able to finish this PR due to bandwidth limitation, I'm planning to implement it inheriting `BaseObject`  from skbase - now potentially `BaseDataset` from `sktime`. I can imagine that this sktime's PR still need some work, and all datasets would need to be adapted, isn't it?

**Comment by fkiraly** [comment]
> I can imagine that this sktime's PR still need some work, and all datasets would need to be adapted, isn't it?

Yes, that's right - it is just a design study at the moment, not even a fully developed API. It was created for the benefit of some contributors who were considering to work on this but then abandoned the project.

So, if you create an API in `prophetverse` and it looks good and adaptable, I would very much also like to adapt it for `sktime`. Or, if you even implement such an interface in `sktime` first, and then "inherit" it in `prophetverse`, that would be even nicer! Either would be appreciated, as I also do not have bandwidth for the data sets module at the moment.

**Comment by felipeangelimvieira** [comment]
Alright, I'll implement it in sktime and then use it in Prophetverse. I'm currently on vacation and should start working on that in about 2 weeks.

**Pull request closed without merging**
